name: second Workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "i am running from the 2nd workflow"
      - name: Multiline Command
        run: |
          node -v
          npm -v